# Generated by Django 4.2 on 2023-04-14 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('left', models.IntegerField(blank=True, null=True)),
                ('right', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Позиция')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.category', verbose_name='Родительская категория')),
            ],
            options={
                'ordering': ('left',),
            },
        ),
    ]
